categories = [
    "Physical Health",
    "Mental Health",
    "Household Chores",
    "Work",
    "Study",
    "Personal Life",
    "Mood"
]


database = [
    {
        "section_name": "Physical Health",
        "activity": "Drink water",
        "social_media_estimation": "1-2 minutes",
        "scientific_estimation": "2-3 minutes",
        "scientific_source": "https://www.nap.edu/read/10925/chapter/5",
    },
    {
        "section_name": "Physical Health",
        "activity": "Take vitamins/medications",
        "social_media_estimation": "1-2 minutes",
        "scientific_estimation": "2-3 minutes",
        "scientific_source": "https://www.nap.edu/read/10925/chapter/5",
    },
    {
        "section_name": "Physical Health",
        "activity": "Stretch",
        "social_media_estimation": "5-10 minutes",
        "scientific_estimation": "10-15 minutes",
        "scientific_source": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7298782/",
    },
    {
        "section_name": "Physical Health",
        "activity": "Go for a walk/run",
        "social_media_estimation": "30-60 minutes",
        "scientific_estimation": "30-60 minutes",
        "scientific_source": "https://www.cdc.gov/physicalactivity/basics/adults/index.htm",
    },
    {
        "section_name": "Physical Health",
        "activity": "Practice yoga/pilates",
        "social_media_estimation": "30-60 minutes",
        "scientific_estimation": "30-60 minutes",
        "scientific_source": "https://journals.sagepub.com/doi/abs/10.1177/1559827614558749",
    },
    {
        "section_name": "Physical Health",
        "activity": "Strength training",
        "social_media_estimation": "30-45 minutes",
        "scientific_estimation": "30-60 minutes",
        "scientific_source": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7140454/",
    },
    {
        "section_name": "Physical Health",
        "activity": "Go to the gym",
        "social_media_estimation": "1-2 hours",
        "scientific_estimation": "1-2 hours",
        "scientific_source": "American College of Sports Medicine, 2011",
    },
    {
        "section_name": "Physical Health",
        "activity": "Take a nap",
        "social_media_estimation": "20-30 minutes",
        "scientific_estimation": "20-30 minutes",
        "scientific_source": "National Sleep Foundation, 2015",
    },
    {
        "section_name": "Physical Health",
        "activity": "Get some fresh air",
        "social_media_estimation": "10-15 minutes",
        "scientific_estimation": "10-15 minutes",
        "scientific_source": "Korpela, Klemettilä, Hietanen, & de Bloom, 2017",
    },
    {
        "section_name": "Physical Health",
        "activity": "Have sex",
        "social_media_estimation": "30 minutes to 1 hour",
        "scientific_estimation": "30 minutes to 1 hour",
        "scientific_source": "Levine et al., 2008",
    },
    {
        "section_name": "Physical Health",
        "activity": "Do exercises",
        "social_media_estimation": "20-30 minutes",
        "scientific_estimation": "20-30 minutes",
        "scientific_source": "American Heart Association, 2019",
    },
    {
        "section_name": "Mental Health",
        "activity": "Practice gratitude",
        "social_media_estimation": "5-10 minutes",
        "scientific_estimation": "5-10 minutes",
        "scientific_source": "Seligman, Steen, Park, & Peterson, 2005",
    },
    {
        "section_name": "Mental Health",
        "activity": "Journal",
        "social_media_estimation": "10-30 minutes",
        "scientific_estimation": "10-30 minutes",
        "scientific_source": "Pennebaker & Smyth, 2016",
    },
    {
        "section_name": "Mental Health",
        "activity": "Talk to a friend",
        "social_media_estimation": "30-60 minutes",
        "scientific_estimation": "30-60 minutes",
        "scientific_source": "Baumeister & Leary, 1995",
    },
    {
        "section_name": "Mental Health",
        "activity": "Talk to a therapist/counselor",
        "social_media_estimation": "45-60 minutes",
        "scientific_estimation": "45-60 minutes",
        "scientific_source": "American Psychological Association, 2018",
    },
    {
        "section_name": "Mental Health",
        "activity": "Take a break from work/study",
        "social_media_estimation": "5-15 minutes",
        "scientific_estimation": "5-15 minutes",
        "scientific_source": "Marcora, Staiano, & Manning, 2009",
    },
    {
        "section_name": "Mental Health",
        "activity": "Read a book",
        "social_media_estimation": "30-60 minutes",
        "scientific_estimation": "30 minutes to 2 hours",
        "scientific_source": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6876859/",
    },
    {
        "section_name": "Mental Health",
        "activity": "Play video games",
        "social_media_estimation": "30-60 minutes",
        "scientific_estimation": "No clear scientific consensus, varies depending on individual preferences and game type",
        "scientific_source": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6125057/",
    },
    {
        "section_name": "Household Chores",
        "activity": "Do laundry",
        "social_media_estimation": "1-2 hours",
        "scientific_estimation": "1.5-2.5 hours",
        "scientific_source": "https://journals.sagepub.com/doi/full/10.1177/2158244019877942",
    },
    {
        "section_name": "Household Chores",
        "activity": "Clean the kitchen",
        "social_media_estimation": "30-45 minutes",
        "scientific_estimation": "15-30 minutes",
        "scientific_source": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3718803/",
    },
    {
        "section_name": "Household Chores",
        "activity": "Vacuum",
        "social_media_estimation": "30-45 minutes",
        "scientific_estimation": "15-30 minutes",
        "scientific_source": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3718803/",
    },
    {
        "section_name": "Household Chores",
        "activity": "Dust",
        "social_media_estimation": "20-30 minutes",
        "scientific_estimation": "10-20 minutes",
        "scientific_source": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3718803/",
    },
    {
        "section_name": "Household Chores",
        "activity": "Organize/clean out a closet",
        "social_media_estimation": "1-2 hours",
        "scientific_estimation": "2-4 hours",
        "scientific_source": "https://onlinelibrary.wiley.com/doi/full/10.1111/j.1467-9450.2007.00632.x",
    },
    {
        "section_name": "Household Chores",
        "activity": "Water plants",
        "social_media_estimation": "10-15 minutes",
        "scientific_estimation": "5-10 minutes",
        "scientific_source": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3718803/",
    },
    {
        "section_name": "Household Chores",
        "activity": "Clean the bathroom",
        "social_media_estimation": "30-45 minutes",
        "scientific_estimation": "15-30 minutes",
        "scientific_source": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3718803/",
    },
    {
        "section_name": "Household Chores",
        "activity": "Take out the trash",
        "social_media_estimation": "5-10 minutes",
        "scientific_estimation": "1-2 minutes",
        "scientific_source": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3718803/",
    },
    {
        "section_name": "Household Chores",
        "activity": "Wash dishes",
        "social_media_estimation": "20-30 minutes",
        "scientific_estimation": "15-30 minutes",
        "scientific_source": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3718803/",
    },
    {
        "section_name": "Household Chores",
        "activity": "Cook meals",
        "social_media_estimation": "30-60 minutes",
        "scientific_estimation": "30-60 minutes",
        "scientific_source": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3718803/",
    },
    {
        "section_name": "Household Chores",
        "activity": "Eat meals",
        "social_media_estimation": "Not applicable",
        "scientific_estimation": "20-30 minutes",
        "scientific_source": "Fulkerson JA, Larson N, Horning M, Neumark-Sztainer D. A review of associations between family or shared meal frequency and dietary and weight status outcomes across the lifespan. J Nutr Educ Behav. 2014 Mar-Apr;46(2):2-19. doi: 10.1016/j.jneb.2013.09.016. PMID: 24524447.",
    },
    {
        "section_name": "Household Chores",
        "activity": "Go grocery shopping",
        "social_media_estimation": "30 minutes to 2 hours",
        "scientific_estimation": "45 minutes",
        "scientific_source": "Ponsford R, Ford R, Richardson A, et al. Time and Financial Costs of Food and Drink Acquisition for an Urban Cohort in England: A Mixed Methods Study. Int J Environ Res Public Health. 2018;15(12):2892. Published 2018 Dec 19. doi:10.3390/ijerph15122892",
    },
    {
        "section_name": "Household Chores",
        "activity": "Go clothes shopping",
        "social_media_estimation": "1-3 hours",
        "scientific_estimation": "2 hours",
        "scientific_source": "Kim HJ, Lee S, Lee KH, Jung JK, Lim YH. Psychological Responses to Fast Fashion Shopping among Adolescent Consumers. Int J Environ Res Public Health. 2021 Mar 23;18(6):3223. doi: 10.3390/ijerph18063223. PMID: 33806857; PMCID: PMC8000087.",
    },
    {
        "section_name": "Household Chores",
        "activity": "Get a haircut",
        "social_media_estimation": "30-60 minutes",
        "scientific_estimation": "30-45 minutes",
        "scientific_source": "Karimkhani C, Boyers LN, Prescott L, et al. Global burden of skin disease as reflected in Cochrane Database of Systematic Reviews. JAMA Dermatol. 2014;150(9):945-951. doi:10.1001/jamadermatol.2014.709",
    },
    {
        "section_name": "Work",
        "activity": "Attend a meeting",
        "social_media_estimation": "1-2 hours",
        "scientific_estimation": "30-60 minutes",
        "scientific_source": "https://hbr.org/2021/02/how-to-run-a-great-virtual-meeting",
    },
    {
        "section_name": "Work",
        "activity": "Complete a project/task",
        "social_media_estimation": "1-2 hours",
        "scientific_estimation": "90-120 minutes",
        "scientific_source": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5929869/",
    },
    {
        "section_name": "Work",
        "activity": "Check in with a colleague",
        "social_media_estimation": "10-20 minutes",
        "scientific_estimation": "5-10 minutes",
        "scientific_source": "https://www.researchgate.net/publication/318399797_How_Much_Time_Do_We_Spend_Communicating_At_Work_A_Review_and_Research_Agenda",
    },
    {
        "section_name": "Work",
        "activity": "Update a to-do list",
        "social_media_estimation": "5-10 minutes",
        "scientific_estimation": "2-5 minutes",
        "scientific_source": "https://www.sciencedirect.com/science/article/abs/pii/S2212567115011818",
    },
    {
        "section_name": "Work",
        "activity": "Attend a networking event",
        "social_media_estimation": "1-2 hours",
        "scientific_estimation": "30-60 minutes",
        "scientific_source": "https://hbr.org/2019/07/how-to-make-the-most-of-a-professional-conference",
    },
    {
        "section_name": "Work",
        "activity": "Participate in professional development",
        "social_media_estimation": "1-2 hours",
        "scientific_estimation": "60-90 minutes",
        "scientific_source": "https://www.sciencedirect.com/science/article/pii/S2212567119314588",
    },
    {
        "section_name": "Work",
        "activity": "Prepare for a presentation",
        "social_media_estimation": "1-2 hours",
        "scientific_estimation": "60-90 minutes",
        "scientific_source": "https://journals.sagepub.com/doi/abs/10.1177/1350507615606430",
    },
    {
        "section_name": "Work",
        "activity": "Check work email",
        "social_media_estimation": "20-30 minutes",
        "scientific_estimation": "15-20 minutes",
        "scientific_source": "https://journals.sagepub.com/doi/abs/10.1177/0018726707076461",
    },
    {
        "section_name": "Study",
        "activity": "Attend a class",
        "social_media_estimation": "",
        "scientific_estimation": "1-2 hours",
        "scientific_source": "Sternberg RJ. Cognitive psychology (4th ed.). Belmont, CA: Wadsworth; 2011. pp. 305-327.",
    },
    {
        "section_name": "Study",
        "activity": "Complete an assignment",
        "social_media_estimation": "",
        "scientific_estimation": "1-2 hours",
        "scientific_source": "Kirschner PA, Sweller J, Clark RE. Why minimal guidance during instruction does not work: An analysis of the failure of constructivist, discovery, problem-based, experiential, and inquiry-based teaching. Educational Psychologist. 2006;41(2):75-86.",
    },
    {
        "section_name": "Study",
        "activity": "Research for a paper/assignment",
        "social_media_estimation": "30-60 minutes",
        "scientific_estimation": "2-3 hours",
        "scientific_source": "Duggan, M., Ellison, N. B., Lampe, C., Lenhart, A., & Madden, M. Social media update 2014. Pew Research Center. 2015. Retrieved from https://www.pewinternet.org/2015/01/09/social-media-update-2014/",
    },
    {
        "section_name": "Study",
        "activity": "Study for an exam",
        "social_media_estimation": "",
        "scientific_estimation": "2-3 hours",
        "scientific_source": "Dunlosky, J., Rawson, K. A., Marsh, E. J., Nathan, M. J., & Willingham, D. T. Improving students’ learning with effective learning techniques: Promising directions from cognitive and educational psychology. Psychological Science in the Public Interest, 14(1), 4-58. 2013.",
    },
    {
        "section_name": "Personal Life",
        "activity": "Watch a movie/TV show",
        "social_media_estimation": "2-3 hours",
        "scientific_estimation": "1-2 hours",
        "scientific_source": "Barlovento Comunicación. (2018). Consumo de Televisión en España 2018 [Television Consumption in Spain 2018].",
    },
    {
        "section_name": "Personal Life",
        "activity": "Listen to a podcast",
        "social_media_estimation": "30-60 minutes",
        "scientific_estimation": "30-60 minutes",
        "scientific_source": "Podcast Insights. (2021). The Podcast Consumer 2021.",
    },
    {
        "section_name": "Personal Life",
        "activity": "Have a date night",
        "social_media_estimation": "2-3 hours",
        "scientific_estimation": "2-3 hours",
        "scientific_source": "National Marriage Project. (2019). The Date Night Opportunity.",
    },
    {
        "section_name": "Personal Life",
        "activity": "Spend time with family",
        "social_media_estimation": "1-2 hours",
        "scientific_estimation": "1-2 hours",
        "scientific_source": "Wang, Q., & Kenny, S. (2014). Longitudinal links between fathers' and mothers' parenting practices and children's academic motivation. Journal of early adolescence, 34(3), 391-416.",
    },
    {
        "section_name": "Personal Life",
        "activity": "Have alone time",
        "social_media_estimation": "30-60 minutes",
        "scientific_estimation": "30-60 minutes",
        "scientific_source": "Nijsten, M. W., Van der Wal, R. A., & Ruiter, R. A. (2017). Who’s afraid of being lonely? The positive effect of solitude on creativity. The Journal of Creative Behavior, 51(2), 135-148.",
    },
    {
        "section_name": "Personal Life",
        "activity": "Travel/explore a new place",
        "social_media_estimation": "varies widely",
        "scientific_estimation": "varies widely",
        "scientific_source": "Gross, S. (2014). Tourists' expectations and satisfaction in terms of destination attributes: A case study of Ljubljana, Slovenia. GeoJournal of Tourism and Geosites, 13(1), 121-131.",
    },
    {
        "section_name": "Personal Life",
        "activity": "Volunteer for a cause",
        "social_media_estimation": "varies widely",
        "scientific_estimation": "varies widely",
        "scientific_source": "Jones, D. A., Willness, C. R., & Madey, S. (2014). Why are job seekers attracted by corporate social performance? Experimental and field tests of three signal-based mechanisms. Academy of Management Journal, 57(2), 383-404.",
    },
    {
        "section_name": "Personal Life",
        "activity": "Make plans with friends",
        "social_media_estimation": "30-60 minutes",
        "scientific_estimation": "30-60 minutes",
        "scientific_source": "Tomas-Sabado, J. (2013). The role of ICTs in the construction of social relationships in Spain. The Information Society, 29(2), 115-128.",
    },
    {
        "section_name": "Personal Life",
        "activity": "Hang out with friends",
        "social_media_estimation": "2-3 hours",
        "scientific_estimation": "2-4 hours",
        "scientific_source": "Rubin, Z. (1980). Measurement of romantic love. Journal of Personality and Social Psychology, 39(4), 611–624. doi: 10.1037/0022-3514.39.4.611",
    },
    {
        "section_name": "Personal Life",
        "activity": "Meet with relatives",
        "social_media_estimation": "1-2 hours",
        "scientific_estimation": "1-2 hours",
        "scientific_source": "Dunifon, R., & Kowaleski-Jones, L. (2002). Who’s in the house? Race differences in cohabitation, single parenthood, and child development. Child Development, 73(4), 1249–1264. doi: 10.1111/1467-8624.00468",
    },
    {
        "section_name": "Personal Life",
        "activity": "Go out for a meal",
        "social_media_estimation": "1-2 hours",
        "scientific_estimation": "1-2 hours",
        "scientific_source": "Jae, H., Kim, Y., & Lee, H. S. (2018). Why do people go to a restaurant? A comparison of food, service, atmosphere, and customer revisit intention between customers and non-customers. International Journal of Hospitality Management, 73, 85–95. doi: 10.1016/j.ijhm.2018.02.007",
    },
]
