import app.constants.key_callbacks
import app.constants.key_texts

CALLBACK_TEXT_MAP = {
    key_callbacks.HEALTH_CALLBACK: key_texts.HEALTH,
    key_callbacks.CHORES_CALLBACK: key_texts.CHORES,
    key_callbacks.WORK_CALLBACK: key_texts.WORK,
    key_callbacks.STUDY_CALLBACK: key_texts.STUDY,
    key_callbacks.MYSELF_CALLBACK: key_texts.MYSELF,
    key_callbacks.ENVIRONMENT_CALLBACK: key_texts.ENVIRONMENT,
    key_callbacks.SOCIAL_CALLBACK: key_texts.SOCIAL,
    key_callbacks.FAMILY_CALLBACK: key_texts.FAMILY,
    key_callbacks.RELATIONSHIP_CALLBACK: key_texts.RELATIONSHIP,
    key_callbacks.MOOD_CALLBACK: key_texts.MOOD,
    key_callbacks.HAPPY_CALLBACK: key_texts.HAPPY,
    key_callbacks.CONTENT_CALLBACK: key_texts.CONTENT,
    key_callbacks.NEUTRAL_CALLBACK: key_texts.NEUTRAL,
    key_callbacks.DISAPPOINTED_CALLBACK: key_texts.DISAPPOINTED,
    key_callbacks.DEPRESSED_CALLBACK: key_texts.DEPRESSED,
    key_callbacks.DISPOSITION_CALLBACK: key_texts.DISPOSITION,
    key_callbacks.CALM_CALLBACK: key_texts.CALM,
    key_callbacks.FRUSTRATED_CALLBACK: key_texts.FRUSTRATED,
    key_callbacks.IRRITATED_CALLBACK: key_texts.IRRITATED,
    key_callbacks.ANNOYED_CALLBACK: key_texts.ANNOYED,
    key_callbacks.ANGRY_CALLBACK: key_texts.ANGRY,
    key_callbacks.PRODUCTIVITY_CALLBACK: key_texts.PRODUCTIVITY,
    key_callbacks.PRODUCTIVE_CALLBACK: key_texts.PRODUCTIVE,
    key_callbacks.MOTIVATED_CALLBACK: key_texts.MOTIVATED,
    key_callbacks.INDECISIVE_CALLBACK: key_texts.INDECISIVE,
    key_callbacks.OVERWHELMED_CALLBACK: key_texts.OVERWHELMED,
    key_callbacks.PROCRASTINATING_CALLBACK: key_texts.PROCRASTINATING,
    key_callbacks.CONFIDENCE_CALLBACK: key_texts.CONFIDENCE,
    key_callbacks.CONFIDENT_CALLBACK: key_texts.CONFIDENT,
    key_callbacks.APPREHENSIVE_CALLBACK: key_texts.APPREHENSIVE,
    key_callbacks.NERVOUS_CALLBACK: key_texts.NERVOUS,
    key_callbacks.STRESSED_CALLBACK: key_texts.STRESSED,
    key_callbacks.ANXIOUS_CALLBACK: key_texts.ANXIOUS,
}
