"""Texts for bot function callbacks."""

HEALTH_CALLBACK = "HEALTH_CALLBACK"
CHORES_CALLBACK = "CHORES_CALLBACK"
WORK_CALLBACK = "WORK_CALLBACK"
STUDY_CALLBACK = "STUDY_CALLBACK"
MYSELF_CALLBACK = "MYSELF_CALLBACK"
ENVIRONMENT_CALLBACK = "ENVIRONMENT_CALLBACK"
SOCIAL_CALLBACK = "SOCIAL_CALLBACK"
FAMILY_CALLBACK = "FAMILY_CALLBACK"
RELATIONSHIP_CALLBACK = "RELATIONSHIP_CALLBACK"

MOOD_CALLBACK = "MOOD_CALLBACK"

HAPPY_CALLBACK = "HAPPY_CALLBACK"
CONTENT_CALLBACK = "CONTENT_CALLBACK"
NEUTRAL_CALLBACK = "NEUTRAL_CALLBACK"
DISAPPOINTED_CALLBACK = "DISAPPOINTED_CALLBACK"
DEPRESSED_CALLBACK = "DEPRESSED_CALLBACK"

DISPOSITION_CALLBACK = "DISPOSITION_CALLBACK"

CALM_CALLBACK = "CALM_CALLBACK"
FRUSTRATED_CALLBACK = "FRUSTRATED_CALLBACK"
IRRITATED_CALLBACK = "IRRITATED_CALLBACK"
ANNOYED_CALLBACK = "ANNOYED_CALLBACK"
ANGRY_CALLBACK = "ANGRY_CALLBACK"

PRODUCTIVITY_CALLBACK = "PRODUCTIVITY_CALLBACK"

PRODUCTIVE_CALLBACK = "PRODUCTIVE_CALLBACK"
MOTIVATED_CALLBACK = "MOTIVATED_CALLBACK"
INDECISIVE_CALLBACK = "INDECISIVE_CALLBACK"
OVERWHELMED_CALLBACK = "OVERWHELMED_CALLBACK"
PROCRASTINATING_CALLBACK = "PROCRASTINATING_CALLBACK"

CONFIDENCE_CALLBACK = "CONFIDENCE_CALLBACK"

CONFIDENT_CALLBACK = "CONFIDENT_CALLBACK"
APPREHENSIVE_CALLBACK = "APPREHENSIVE_CALLBACK"
NERVOUS_CALLBACK = "NERVOUS_CALLBACK"
STRESSED_CALLBACK = "STRESSED_CALLBACK"
ANXIOUS_CALLBACK = "ANXIOUS_CALLBACK"
# Service buttons
GO_BACK_CALLBACK = "GO_BACK_CALLBACK"
FEEDBACK_CALLBACK = "FEEDBACK_CALLBACK"
TRACK_CALLBACK = "TRACK_CALLBACK"
INSIGHTS_CALLBACK = "INSIGHTS_CALLBACK"
MAIN_MENU_CALLBACK = "MAIN_MENU_CALLBACK"
START_CALLBACK = "START_CALLBACK"
HELP_CALLBACK = "HELP_CALLBACK"

REASON_CAUSE_CALLBACKS = [
    HAPPY_CALLBACK,
    CONTENT_CALLBACK,
    NEUTRAL_CALLBACK,
    DISAPPOINTED_CALLBACK,
    DEPRESSED_CALLBACK,
    CALM_CALLBACK,
    FRUSTRATED_CALLBACK,
    IRRITATED_CALLBACK,
    ANNOYED_CALLBACK,
    ANGRY_CALLBACK,
    PRODUCTIVE_CALLBACK,
    MOTIVATED_CALLBACK,
    INDECISIVE_CALLBACK,
    OVERWHELMED_CALLBACK,
    PROCRASTINATING_CALLBACK,
    CONFIDENT_CALLBACK,
    APPREHENSIVE_CALLBACK,
    NERVOUS_CALLBACK,  # TODO: Rework this list item
    STRESSED_CALLBACK,
    ANXIOUS_CALLBACK,
]

AFTER_REASON_CALLBACKS = [
    HEALTH_CALLBACK,
    CHORES_CALLBACK,
    WORK_CALLBACK,
    STUDY_CALLBACK,
    MYSELF_CALLBACK,
    ENVIRONMENT_CALLBACK,
    SOCIAL_CALLBACK,
    FAMILY_CALLBACK,
    RELATIONSHIP_CALLBACK,
]
# Insights section
DAILY_TIME_CHART_CALLBACK = "DAILY_TIME_CHART_CALLBACK"
WEEKLY_TIME_CHART_CALLBACK = "WEEKLY_TIME_CHART_CALLBACK"
MONTHLY_TIME_CHART_CALLBACK = "MONTHLY_TIME_CHART_CALLBACK"
BALANCE_WHEEL_CHART_CALLBACK = "BALANCE_WHEEL_CHART_CALLBACK"
